# Demystifying Neural Networks 

---

# Exercises - Concepts

We will do these *on paper* first and then in `numpy`.

In [1]:
import numpy as np

#### 1. Evaluate (on paper) the dot product of

A) $\vec{x} = [3, 7]$ and $\vec{y} = [5, 12]$

B) $\vec{x} = [1, -6, 11]$ and $\vec{y} = [2, 4, -8]$

C) $\vec{x} = [2, 2, -7, 9, 3]$ and $\vec{y} = [1, 1, 1, 0, 1]$

A) $3 \cdot 5 + 7 \cdot 12 = 15 + 84 = 99$

B) $1 \cdot 2 + (-6) \cdot 4 + 11 \cdot (-8) = 2 -24 - 88 = -110$

C) $2 \cdot 1 + 2 \cdot 1 + (-7) \cdot 1 + 9 \cdot 0 + 3 \cdot 1 = 2 + 2 -7 + 3 = 0$

#### 2. Evaluate the previous exercise using `numpy` arrays (use `np.dot` or `@`)

In [2]:
x1 = np.array([3, 7])
y1 = np.array([5, 12])
print(x1 @ y1)
x2 = np.array([1, -6, 11])
y2 = np.array([2,  4, -8])
print(x2 @ y2)
x3 = np.array([2, 2, -7, 9, 3])
y3 = np.array([1, 1,  1, 0, 1])
print(x3 @ y3)

99
-110
0


#### 3. Evaluate (on paper) the following matrix multiplications

$$
A =
\left[
\begin{matrix}
1 &  7 &  5 &  7 \\
3 &  3 & -1 & -6 \\
1 & -3 &  1 & 11 \\
\end{matrix}
\right] \\
B =
\left[
\begin{matrix}
0 &  3 &  5 \\
2 &  2 & -1 \\
0 & -3 &  1 \\
1 &  0 & -1 \\
\end{matrix}
\right] \\
$$

A) $A \cdot B =$

B) $B \cdot A =$

A)

$$
\left[
\begin{matrix}
1 &  7 &  5 &  7 \\
3 &  3 & -1 & -6 \\
1 & -3 &  1 & 11 \\
\end{matrix}
\right] \cdot
\left[
\begin{matrix}
0 &  3 &  5 \\
2 &  2 & -1 \\
0 & -3 &  1 \\
1 &  0 & -1 \\
\end{matrix}
\right] \\
=
\left[
\begin{matrix}
1 \cdot 0 +   7  \cdot   2  +   5  \cdot   0  +   7  \cdot   1  &
1 \cdot 3 +   7  \cdot   2  +   5  \cdot (-3) +   7  \cdot   0  &
1 \cdot 5 +   7  \cdot (-1) +   5  \cdot   1  +   7  \cdot (-1) \\
3 \cdot 0 +   3  \cdot   2  + (-1) \cdot   0  + (-6) \cdot   1  &
3 \cdot 3 +   3  \cdot   2  + (-1) \cdot (-3) + (-6) \cdot   0  &
3 \cdot 5 +   3  \cdot (-1) + (-1) \cdot   1  + (-6) \cdot (-1) \\
1 \cdot 0 + (-3) \cdot   2  +   1  \cdot   0  +  11  \cdot   1  &
1 \cdot 3 + (-3) \cdot   2  +   1  \cdot (-3) +  11  \cdot   0  &
1 \cdot 5 + (-3) \cdot (-1) +   1  \cdot   1  +  11  \cdot (-1) \\
\end{matrix}
\right] \\
=
\left[
\begin{matrix}
21 &  2 & -4 \\
 0 & 18 & 17 \\
 5 & -6 & -2 \\
\end{matrix}
\right]
$$

B)

$$
\left[
\begin{matrix}
0 &  3 &  5 \\
2 &  2 & -1 \\
0 & -3 &  1 \\
1 &  0 & -1 \\
\end{matrix}
\right] \cdot
\left[
\begin{matrix}
1 &  7 &  5 &  7 \\
3 &  3 & -1 & -6 \\
1 & -3 &  1 & 11 \\
\end{matrix}
\right]
=
\left[
\begin{matrix}
0 \cdot 1 +   3  \cdot   3  +   5  \cdot   1  &
0 \cdot 7 +   3  \cdot   3  +   5  \cdot (-3) &
0 \cdot 5 +   3  \cdot (-1) +   5  \cdot   1  &
0 \cdot 7 +   3  \cdot (-6) +   5  \cdot  11  \\
2 \cdot 1 +   2  \cdot   3  + (-1) \cdot   1  &
2 \cdot 7 +   2  \cdot   3  + (-1) \cdot (-3) &
2 \cdot 5 +   2  \cdot (-1) + (-1) \cdot   1  &
2 \cdot 7 +   2  \cdot (-6) + (-1) \cdot  11  \\
0 \cdot 1 + (-3) \cdot   3  +   1  \cdot   1  &
0 \cdot 7 + (-3) \cdot   3  +   1  \cdot (-3) &
0 \cdot 5 + (-3) \cdot (-1) +   1  \cdot   1  &
0 \cdot 7 + (-3) \cdot (-6) +   1  \cdot  11  \\
1 \cdot 1 +   0  \cdot   3  + (-1) \cdot   1  &
1 \cdot 7 +   0  \cdot   3  + (-1) \cdot (-3) &
1 \cdot 5 +   0  \cdot (-1) + (-1) \cdot   1  &
1 \cdot 7 +   0  \cdot (-6) + (-1) \cdot  11  &
\end{matrix}
\right] \\
=
\left[
\begin{matrix}
14 &  -6 & 2 & 37 \\
 7 &  23 & 7 & -9 \\
-8 & -12 & 4 & 29 \\
 0 &  10 & 4 & -4 \\
\end{matrix}
\right]
$$

#### 4. Evaluate the previous exercise using `numpy` arrays (use `np.dot` or `@`)

In [3]:
A = np.array([
    [1,  7,  5,  7],
    [3,  3, -1, -6],
    [1, -3,  1, 11],
])
B = np.array([
    [0,  3,  5],
    [2,  2, -1],
    [0, -3,  1],
    [1,  0, -1],
])
print(A @ B)
print(B @ A)

[[21  2 -4]
 [ 0 18 17]
 [ 5 -6 -2]]
[[ 14  -6   2  37]
 [  7  23   7  -9]
 [ -8 -12   4  29]
 [  0  10   4  -4]]


#### 5. Evaluate a network forward pass

Using the matrices below as the ones in the ANN picture ($W, W_B, W', W'_B, W'', W''_B$)
evaluate the vector $\vec{x} = [3, 7]$ passing through the network.

Note: remember to evaluate the activation function (`np.tanh`).

In [4]:
W = np.array([
    [ .5, .3],
    [-.3, .2],
    [ .1, .1],
])
W_B = np.array([.5, .2, -.1])
Wx = np.array([
    [.3, -.5, .6],
    [.1, -.1, .9],
])
Wx_B = np.array([.1, .1])
Wxx = np.array([
    [.3, .6],
    [.1, .9],
])
Wxx_B = np.array([-.1, .2])

In [5]:
x = np.array([3., 7.])
y_hat = np.tanh(Wxx @ np.tanh(Wx @ np.tanh(W @ x + W_B) + Wx_B) + Wxx_B)
print(y_hat)

[0.41205389 0.68471057]
